version: '3.3'

services:
  web:
    build: ./
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./ecom/:/usr/src/ecom/
    ports:
      - 8000:8000
    env_file:
      - ./ecom/.env
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=eureka
      - POSTGRES_DB=dbtest

volumes:
  postgres_data:

